### ISSUE TITLE
Make postBuild executable automatically

### ISSUE THREAD

**Issue by kmader** [jupyter/repo2docker#243] opened 2018-02-21 13:06 UTC
If a repository is originally created on windows the postBuild will not be executable. If you clone this repo on linux and then ```chmod a+x postBuild``` and then add, commit, push the status does not get transferred to github. So you can run repo2docker locally without any problem but on the same repository it doesn't work. You then are required to manually ```git update-index --chmod=+x postBuild``` in order force the file to be executable. 

Would it not be better to have repo2docker do this step manually before building? It would make creating repos from windows much easier. (example repo https://github.com/4QuantOSS/FastPhotoStyle/commits/master)

**Comment by betatim** [comment] 2018-02-22 08:26
(Related #240 and #241)

Since a few days `postBuild` isn't required to be executable any more. I'll close this for now, feel free to reopen.

**Closed by betatim** 2018-02-22 08:26 UTC

**Comment by kmader** [comment] 2018-02-22 22:12
@betatim still throwing the message
```
Error during build: binder/postBuild is not executable, see http://repo2docker.readthedocs.io/en/latest/samples.html#system-post-build-scripts for help.
```
Have the updates made it to production binder yet?

**Comment by betatim** [comment] 2018-02-23 14:40
https://github.com/jupyterhub/mybinder.org-deploy/pull/477 should have deployed them, the deploy was close to when you posted so might have just missed it. (When I closed this I thought we had already deployed it)

**Comment by kmader** [comment] 2018-03-08 18:22
still an issue
```
Waiting for build to start...
Cloning into '/tmp/repo2docker_dk5z2em'...
HEAD is now at 702684b first binder friendly version
Building conda environment for python=3.6Error during build: binder/postBuild is not executable, see http://repo2docker.readthedocs.io/en/latest/samples.html#system-post-build-scripts for help.
```

**Comment by betatim** [comment] 2018-03-08 22:01
Ran into the same problem earlier today. Failing to reproduce it when I run `repo2docker` locally though.
