### ISSUE TITLE
Packages picked up from the `conda-forge/label/broken`

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyter/repo2docker#626] opened 2019-03-21 21:21 UTC
It seems that the addition of `conda-forge/label/broken` channel even as a lower-priority channel causes packages to be picked up from that channel.

An example of repository impacted is xeus-python: https://mybinder.org/v2/gh/QuantStack/xeus-python/stable?filepath=notebooks/xeus-python.ipynb

**Comment by betatim** [comment] 2019-03-21 22:17
My guess right now is that this is happening because we "freeze" notebook to 5.7.4 (https://github.com/jupyter/repo2docker/blob/master/repo2docker/buildpacks/conda/environment.yml) which is [marked as broken on conda-forge](https://anaconda.org/conda-forge/notebook/labels).

At least that is how I understand how to find out what is in the broken channel. Is there a better way?

Trying to find out why it was marked as broken but my guess is [this CVE](https://blog.jupyter.org/jupyter-notebook-xssi-security-fix-546cd95babb0).

To fix this we should bump the notebook we "freeze" to a newer version. This would be a good move anyway.

**Comment by betatim** [comment] 2019-03-21 22:55
After chatting with @mariusvniekerk about conda-forge I am now confident that we should bump the notebook package. There is probably no easy way to find out why it got marked as broken.

**Comment by SylvainCorlay** [comment] 2019-03-22 08:02
I would argue that we should completely drop the broken channel. A package may be marked as broken for many reason, such as a wrong spec for a dependency (to loose contraint).

This would cause the package to be considered as a solution to the set of SAT constraints by the solver.

**Comment by SylvainCorlay** [comment] 2019-03-22 08:04
Also if a package version is unavailable in the standard channel, one can always create a branch in the feedstock to properly package that version.

**Comment by betatim** [comment] 2019-03-22 13:56
The motivation for adding the broken channel as the lowest priority is to allow exactly the case were a package version that someone pinned explicitly to continue to be installed after it got marked as broken. I think if we drop the channel builds would fail instead of reproducing the environment the author originally specified.

In this particular case dropping the broken channel would mean all builds with repo2docker would fail because notebook 5.7.4 isn't available any more and that is the version that is pinned in repo2docker.

The solution to this particular problem is to bump the version of the notebook package we pin via https://repo2docker.readthedocs.io/en/latest/contributing/tasks.html#update-and-freeze-buildpack-dependencies

**Closed** 2019-03-24 07:09 UTC
