### ISSUE TITLE
spurious repo2docker exit code of 1

### ISSUE THREAD

**Issue by jhamman** [jupyter/repo2docker#566] opened 2019-01-26 18:58 UTC
I'm using repo2docker v0.7.0. I have a build that seems to complete without error but consistantly returns an exit code of 1. For example, the tail of my [log](https://travis-ci.com/pangeo-data/pangeo-stacks/jobs/173219607) looks like:

```
...
 ---> Running in 33d7285a097b
Enabling notebook extension jupyter-js-widgets/extension...
      - Validating: OK
 ---> 542c09719695
Removing intermediate container 33d7285a097b
{"aux": {"ID": "sha256:542c09719695e896701e6df72ff261d1fd2e255e89ba3b072e693f690859e3b4"}}Successfully built 542c09719695
Successfully tagged pangeo/base-notebook:2019.01.26
The command "repo2docker ${R2D_ARGS} --no-run --user-name=jovyan --user-id 1000 --appendix="`cat appendix.txt`" --image-name=${IMAGE_NAME} ./${IMAGE}" exited with 1.
```

So the last line coming from r2d is that it successfully tagged my image. Then it tells me it exited with 1. Any ideas on why this would be happening and/or how to diagnose the observed behavior?

**Comment by minrk** [comment] 2019-02-11 12:00
This is very strange. How reproducible is it? I've poked around and don't see anything obvious.

The thing I would to do debug is:

    python -m pdb $(which jupyter-repo2docker) ${R2D_ARGS}...

You might also want to [break on exit](https://stackoverflow.com/questions/42835017/cathing-sys-exit-in-debugger) when you do that

**Comment by jhamman** [comment] 2019-02-11 17:16
You know what, this seems to have gone away. It was quite consistent for a few days on Travis but seems to have gone away. I've also bumped to repo2docker master so maybe that fixed this.

**Comment by yuvipanda** [comment] 2019-05-21 18:25
Going to close this since @jhamman reports it's gone away :) Please re-open if it comes back.

**Closed by yuvipanda** 2019-05-21 18:25 UTC
Labels: bug
