### ISSUE TITLE
r-cran-* binaries fail to install when specifying R version in runtime.txt

### ISSUE THREAD

**Issue by brooksambrose** [jupyter/repo2docker#821] opened 2019-11-27 18:14 UTC
### Bug description

Using R buildpack: when specifying `r-3.6-2019-09-24` in runtime.txt installing `r-cran-*` binaries using apt.txt fails. 

Error references wrong R version `r-api-3.4` which is usually installed with `r-base-core`. Possibly related to #813. 

#### Expected behaviour

`r-cran-*` binaries install with all dependencies.

#### Actual behaviour

Install fails with error output (from mybinder.org and locally with latest repo2docker). This example tries to install `r-cran-crosstalk` but also fails with any other binary:

```Docker
Step 55/71 : RUN apt-get -qq update && apt-get install --yes --no-install-recommends r-cran-crosstalk && apt-get -qq purge && apt-get -qq clean && rm -rf /var/lib/apt/lists/*
 ---> Running in 46e19b8d69df
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 r-cran-crosstalk : Depends: r-api-3.4
                    Depends: r-cran-htmltools (>= 0.3.5) but it is not going to be installed
                    Depends: r-cran-jsonlite but it is not going to be installed
                    Depends: r-cran-lazyeval but it is not going to be installed
                    Depends: r-cran-r6 but it is not going to be installed
                    Depends: r-cran-shiny (>= 0.11) but it is not going to be installed
                    Depends: r-cran-ggplot2 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
Removing intermediate container 46e19b8d69df
The command '/bin/sh -c apt-get -qq update && apt-get install --yes --no-install-recommends r-cran-crosstalk && apt-get -qq purge && apt-get -qq clean && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100
```

### How to reproduce

1. Example [repo](https://github.com/brooksambrose/studio/tree/minpro).
1. Or [![Binder](https://mybinder.org/badge.svg)](https://mybinder.org/v2/gh/brooksambrose/studio/minpro?urlpath=rstudio)
1. Or 
```
jupyter-repo2docker --ref origin/minpro --no-run --debug https://github.com/brooksambrose/studio
```

### Your personal set up

- mybinder.org

**Comment by betatim** [comment] 2019-11-27 18:32
This is a duplicate of #813 so I'll close this.

**Comment by betatim** [comment] 2019-11-27 18:34
Maybe this is only kinda a duplicate.

**Comment by brooksambrose** [comment] 2019-11-27 22:54
FWIW, before being able to specify the R version r-cran binaries did work with the R buildpack.

Not sure how to test, but from [this][https://askubuntu.com/questions/1068356/ive-failed-to-install-the-r-package-broken-packages] could it be as simple as adding to the apt-repository list?

`deb https://cloud.r-project.org/bin/linux/ubuntu bionic-cran35/`

**Comment by betatim** [comment] 2019-11-28 08:48
When we introduced support for different versions of R (via https://cran.r-project.org/bin/linux/ubuntu/README.html) we added the following to the apt repository list:

https://github.com/jupyter/repo2docker/blob/master/repo2docker/buildpacks/r.py#L236

Before we had support for this the default version of R was 3.4 so the `r-cran-*` packages in your `apt.txt` must have come from the default Ubuntu repository (if they even have them?). What happens if you switch to R 3.4 in your `runtime.txt`? This should restore the old behaviour.

**Comment by brooksambrose** [comment] 2019-11-29 20:35
Yeah 3.4 works and it pulls from `http://archive.ubuntu.com/ubuntu bionic/main`
```
 ---> ecb1a25f42de
Step 52/62 : RUN apt-get -qq update && apt-get install --yes --no-install-recommends r-cran-crosstalk && apt-get -qq purge && apt-get -qq clean && rm -rf /var/lib/apt/lists/*
 ---> Running in 82d763cfbe1a
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  fonts-font-awesome fonts-glewlwyd libjs-bootstrap libjs-d3 libjs-es5-shim
  libjs-highlight.js libjs-jquery libjs-jquery-datatables
  libjs-jquery-metadata libjs-jquery-selectize.js libjs-jquery-tablesorter
  libjs-jquery-ui libjs-json libjs-microplugin.js libjs-sifter.js
  libjs-twitter-bootstrap libjs-twitter-bootstrap-datepicker littler
  r-cran-assertthat r-cran-cli r-cran-colorspace r-cran-crayon
  r-cran-dichromat r-cran-digest r-cran-ggplot2 r-cran-glue r-cran-gtable
  r-cran-htmltools r-cran-httpuv r-cran-jsonlite r-cran-labeling
  r-cran-lazyeval r-cran-littler r-cran-magrittr r-cran-mime r-cran-munsell
  r-cran-pillar r-cran-pkgkitten r-cran-plyr r-cran-r6 r-cran-rcolorbrewer
  r-cran-rcpp r-cran-reshape2 r-cran-rlang r-cran-scales r-cran-shiny
  r-cran-sourcetools r-cran-stringi r-cran-stringr r-cran-tibble r-cran-utf8
  r-cran-viridislite r-cran-xtable
Suggested packages:
  libjs-jquery-ui-docs r-cran-testthat r-cran-mockery r-cran-withr
  r-cran-kernlab r-cran-mvtnorm r-cran-vcd r-cran-shinyjs r-cran-hexbin
  r-cran-hmisc r-cran-mapproj r-cran-maps r-cran-multcomp r-cran-quantreg
  r-cran-knitr r-cran-dbi r-cran-rsqlite r-cran-r.utils r-cran-forcats
  r-cran-markdown r-cran-httr r-cran-curl r-cran-sp r-cran-getopt r-cran-abind
  r-cran-foreach r-cran-doparallel r-cran-iterators r-cran-inline r-cran-bit64
  r-cran-hms r-cran-cairo r-cran-htmlwidgets r-cran-dplyr r-cran-lsmeans
  r-cran-spdep r-cran-zoo
Recommended packages:
  javascript-common
The following NEW packages will be installed:
  fonts-font-awesome fonts-glewlwyd libjs-bootstrap libjs-d3 libjs-es5-shim
  libjs-highlight.js libjs-jquery libjs-jquery-datatables
  libjs-jquery-metadata libjs-jquery-selectize.js libjs-jquery-tablesorter
  libjs-jquery-ui libjs-json libjs-microplugin.js libjs-sifter.js
  libjs-twitter-bootstrap libjs-twitter-bootstrap-datepicker littler
  r-cran-assertthat r-cran-cli r-cran-colorspace r-cran-crayon
  r-cran-crosstalk r-cran-dichromat r-cran-digest r-cran-ggplot2 r-cran-glue
  r-cran-gtable r-cran-htmltools r-cran-httpuv r-cran-jsonlite r-cran-labeling
  r-cran-lazyeval r-cran-littler r-cran-magrittr r-cran-mime r-cran-munsell
  r-cran-pillar r-cran-pkgkitten r-cran-plyr r-cran-r6 r-cran-rcolorbrewer
  r-cran-rcpp r-cran-reshape2 r-cran-rlang r-cran-scales r-cran-shiny
  r-cran-sourcetools r-cran-stringi r-cran-stringr r-cran-tibble r-cran-utf8
  r-cran-viridislite r-cran-xtable
0 upgraded, 54 newly installed, 0 to remove and 32 not upgraded.
Need to get 17.0 MB of archives.
After this operation, 45.3 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu bionic/main amd64 libjs-jquery all 3.2.1-1 [152 kB]
... etc. etc.
```

**Comment by betatim** [comment] 2019-12-09 10:18
Should we close this then? I think the issue was caused by trying to combine R binaries with APT packages for R packages from a different APT mirror. The solution was to use one consistent mirror (in this case this means R 3.4 as only option).

(I'll default to close to save us some clicks, please reopen it if you disagree Brooks)

**Closed by betatim** 2019-12-09 10:18 UTC

**Comment by brooksambrose** [comment] 2019-12-10 03:34
Reading more about community practice, this should be possible with arbitrary versions of ubuntu and/or R using [`ppa:marutter/c2d4u`](https://launchpad.net/~marutter/+archive/ubuntu/c2d4u) as explained for example:

- https://cran.r-project.org/bin/linux/ubuntu/README.html#administration-and-maintances-of-r-packages
- https://youtu.be/qIjWirNma-8?t=90
- https://github.com/rstudio/shinyapps-package-dependencies/issues/4

You and @cboettig were also discussing this last year https://github.com/jupyter/repo2docker/issues/412#issuecomment-443409982, so wondering if adding the PPA is more possible now since r2d had evolved?

**Comment by betatim** [comment] 2019-12-10 12:54
Using https://cran.r-project.org/bin/linux/ubuntu/README.html#administration-and-maintances-of-r-packages brings us back to #813 

I think https://launchpad.net/~marutter/+archive/ubuntu/c2d4u is different from the PPA described on https://cran.r-project.org/bin/linux/ubuntu/README.html. The maintainers from the latter said on their mailing list that only the latest version of R is supported by their PPA. I couldn't find any documentation for the c2d4u PPA regarding which versions of R they support and for how long.

I don't think we will be letting users add custom PPAs. It feels like a lot of them make very specific assumptions about who you are/what you are doing. Also it seems they tend to be "rolling" in terms of the versions they provide which makes it hard to write a spec for a container now that will still work in a few releases (of the PPA) time.
