### ISSUE TITLE
runtime.txt for installing R and requirements.txt clashing

### ISSUE THREAD

**Issue by fomightez** [jupyter/repo2docker#751] opened 2019-07-23 02:31 UTC
Previously, I was installing R/RSTudio using `runtime.txt` and designating some Python packages to install in same build with `requirements.txt`. ([This repository](https://github.com/fomightez/b-roll-binder) allowed me to launch sessions up until today when I rebuilt it to add a `start` script.) Now this combination of `runtime.txt` and `requirements.txt` doesn't work.  
I made a simpler repository to demonstrate as the one I was working with when I found this issue is rather complex.  

TEST EXAMPLE:   
repo: https://github.com/fomightez/testruntimeANDreqs
binder launch link: https://mybinder.org/v2/gh/fomightez/testruntimeANDreqs/master (currently fails to build)

ERROR SEEN:  
```bash
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
Removing intermediate container 927ccc3e1883
The command '/bin/sh -c ${KERNEL_PYTHON_PREFIX}/bin/pip install --no-cache-dir -r "requirements.txt"' returned a non-zero code: 1
```

NOTE:  
Hiding `runtime.txt` by appending `.` in front makes `requirements.txt` be seen again and build works. However, there is no R then.

**Comment by betatim** [comment] 2019-07-23 05:36
Thanks for finding and reporting this. Inn particular for reporting it with a nice example that reproduces the problem! I've made a PR that fixes this. The problem was introduced with a recent change to try and be smart about copying individual files over before the whole repo.

**Comment by fomightez** [comment] 2019-07-23 14:11
MyBinder/Binder makes it so easy to test and demonstrate issues effectively. :-)

**Comment by betatim** [comment] 2019-07-23 14:38
(Let's keep this open till the PR is merged)

**Closed** 2019-07-23 20:15 UTC
