### ISSUE TITLE
Separate URLs for multiple URL options in output

### ISSUE THREAD

**Issue by jzf2101** [jupyter/repo2docker#416] opened 2018-09-26 06:56 UTC
I tried building the jupyterlab demo on repo2docker and got a URL that doesn't work

```
http://(c2229ee5bf32 or 127.0.0.1):60862/?token=e719f34b394ead47ad1f74704f1154767222e26a3fc222d7
```

Can we fix this?

**Comment by betatim** [comment] 2018-09-26 07:05
This URL is printed by the jupyter notebook server. This means that we'd have to take it up with them or find a way to extract the needed information (token and port) from the running server so we can print it ourselves in the format we want it.

**Comment by gnestor** [comment] 2018-11-29 17:38
Is this still an issue? If so, how can I reproduce?

**Comment by betatim** [comment] 2018-11-30 07:59
I think this is fixed now. If I recall correctly the problem was that you can't just paste the printed URL into your browser but instead need to know how to deal with `(c2229ee5bf32 or 127.0.0.1)` by hand.

Now repo2docker only prints one host. I'll close this.

**Closed by betatim** 2018-11-30 08:00 UTC
Labels: bug
