### ISSUE TITLE
software install issues with RStudio

### ISSUE THREAD

**Issue by ctb** [jupyter/repo2docker#253] opened 2018-03-11 01:07 UTC
When running RStudio from binder in https://github.com/ngs-docs/2018-ggg-rstudio-bioinformatics-ws, RStudio needs to install new packages in order to support an RMarkdown document - despite those packages being in `install.R` already!

To replicate --

* make the binder thingy go
* in RStudio, go to 'New File... RMarkdown document'
* see dialog saying "we need a bunch of packages"  (screenshot below)
* note that all the packages are in install.R already!? and boggle.

<img width="477" alt="screen shot 2018-03-10 at 5 06 37 pm" src="https://user-images.githubusercontent.com/51016/37248366-719ec5c8-2485-11e8-9fd0-8ff63fbc164e.png">

**Comment by ctb** [comment] 2018-03-11 01:29
(the install works fine, but it's annoying to spend 5 more minutes installing packages that should? already be installed. And it also points to a problem in repo2docker, maybe.)

**Comment by betatim** [comment] 2018-03-11 07:32
This is a duplicate of #237. It also contains a workaround and an idea for a proper fix, but is lacking someone to do it.

**Closed by betatim** 2018-03-11 07:32 UTC

**Comment by ctb** [comment] 2018-03-11 14:08
thanks!
